// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSN7HabXG76Lpa1KP27IvbHNvbzCqNLJ4',
    appId: '1:330931863296:web:e1bd629bde33fc208abde5',
    messagingSenderId: '330931863296',
    projectId: 'user-management-app-745cb',
    authDomain: 'user-management-app-745cb.firebaseapp.com',
    storageBucket: 'user-management-app-745cb.firebasestorage.app',
    measurementId: 'G-W0W8V1W2XN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAV5ZYFYA0-qUgx6ydXb-aVZq1Lfn2MlOs',
    appId: '1:330931863296:android:d1640663c28436d38abde5',
    messagingSenderId: '330931863296',
    projectId: 'user-management-app-745cb',
    storageBucket: 'user-management-app-745cb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0SbXh4cX78XTnoRpAUfW1aAFscstmc8o',
    appId: '1:330931863296:ios:999b09fb6622f2068abde5',
    messagingSenderId: '330931863296',
    projectId: 'user-management-app-745cb',
    storageBucket: 'user-management-app-745cb.firebasestorage.app',
    iosBundleId: 'com.example.userManagementApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0SbXh4cX78XTnoRpAUfW1aAFscstmc8o',
    appId: '1:330931863296:ios:999b09fb6622f2068abde5',
    messagingSenderId: '330931863296',
    projectId: 'user-management-app-745cb',
    storageBucket: 'user-management-app-745cb.firebasestorage.app',
    iosBundleId: 'com.example.userManagementApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSN7HabXG76Lpa1KP27IvbHNvbzCqNLJ4',
    appId: '1:330931863296:web:63c9b4aa8fcbf4698abde5',
    messagingSenderId: '330931863296',
    projectId: 'user-management-app-745cb',
    authDomain: 'user-management-app-745cb.firebaseapp.com',
    storageBucket: 'user-management-app-745cb.firebasestorage.app',
    measurementId: 'G-TSVQ4PJ9S2',
  );
}
